#!/bin/bash

set -euo pipefail

echo "pre-commit started"

export GO111MODULE="on"
export GOBIN=$(pwd)/bin

if [ ! -f "$(pwd)/bin/exhaustive" ]; then
    go get -u github.com/nishanths/exhaustive/...
fi

make test

echo "pre-commit finished"
